### ISSUE TITLE
PBKDF2

### ISSUE THREAD

**Issue by penn5** [korlibs/krypto#16]

**Comment by penn5** [comment]
Sorry about the massive number of requests :D
I'll donate some soon

**Comment by ln-12** [comment]
I would also really love to see PBKDF2 👍

**Comment by penn5** [comment]
> I would also really love to see PBKDF2, I need the `PBKDF2WithHmacSHA256` function 👍

I even donated and nothing :'(

**Comment by ln-12** [comment]
I just noted there was already and pull request regarding PBKDF2: https://github.com/korlibs/krypto/pull/22

**Comment by penn5** [comment]
Huh. Missed that
