### ISSUE TITLE
Any plan to support kotlin 1.4?

### ISSUE THREAD

**Issue by gotamafandy** [korlibs/krypto#28]
hi, just curious if there is any timeline to support kotlin 1.4?

**Comment by soywiz** [comment]
This week. We will update all the libraries to the latest Kotlin version, though for we checked on Korge 2.0, there are some regressions that might require adjustments, then we will start working on 2.0 of the libraries.

**Comment by soywiz** [comment]
Released 1.12.0 compiled against Kotlin 1.4: https://github.com/korlibs/krypto/releases/tag/v1.12.0
