### ISSUE TITLE
base64 url safe encoder

### ISSUE THREAD

**Issue by ln-12** [korlibs/krypto#30]
Currently, the base64 encoder is not url safe. It would be nice to have an option for that. According to the [RFC 4648](https://tools.ietf.org/html/rfc4648#page-7), you just have to replace the "+" and "/" [here](https://github.com/korlibs/krypto/blob/master/krypto/src/commonMain/kotlin/com/soywiz/krypto/encoding/Base64.kt#L4) with "-" and "_".

**Comment by soywiz** [comment]
Contributions welcome here:

https://github.com/korlibs/krypto/blob/47796f1f99a4daffa4d68b23cbe56e855376eca2/krypto/src/commonMain/kotlin/com/soywiz/krypto/encoding/Base64.kt#L90

A proposal would be:

```
fun ByteArray.toBase64UrlSafe(): String
```
