### ISSUE TITLE
Restore SecureRandom open class + companion object while not causing mutability exceptions on K/N

### ISSUE THREAD

**Issue by soywiz** [korlibs/krypto#34]
Relates to https://github.com/korlibs/krypto/pull/33

**Comment by soywiz** [comment]
Hey @IgnacioCarrionN , do you think could you make a PR with this?

**Comment by IgnacioCarrionN** [comment]
Sure! How can I test the mutability in K/N?

**Comment by soywiz** [comment]
I think the change you did was ok (moving the class temp property into the local function), since that's what could cause a mutability exception on Kotlin/Native when using the object, also you tested it already when you changed it to use the object instead of a new instance. So the only thing remaining is to restore the capability of overriding the class. object -> open class + companion object
