### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by hovi** [korlibs/krypto#4]
Hey, are you gonna deploy new version somewhere? I found only 0.4.0 in jcenter repo and that is quite old different from the code here ;)
Cheers!

**Comment by saschpe** [comment]
It's on jCenter now: https://bintray.com/soywiz/soywiz/krypto

**Comment by hovi** [comment]
Thanks! Is there artifact for kotlin multiplatform projects? Can't see it there.

**Comment by andylamax** [comment]
What is the latest version of this library? I can't seem to get anything except 0.4.0 which as stated above it is outdated

**Comment by soywiz** [comment]
https://bintray.com/korlibs/korlibs/krypto
1.8.1 is compiled against Kotlin 1.3.50
