### ISSUE TITLE
Missing Android published libraries

### ISSUE THREAD

**Issue by felipehjcosta** [korlibs/krypto#9]
I noticed that there isn't any new library for Android platform published into [bintray](https://dl.bintray.com/korlibs/korlibs/com/soywiz/korlibs/krypto/) after 1.7.1 although the others platforms have new version. Is the Android platform deprecated?

**Comment by soywiz** [comment]
Not intended. I will check this for the next release batch

**Comment by soywiz** [comment]
1.8.2 should have the android artifact published
